"""esquema inicial: usuarios, sesiones, corpus y biblioteca de estudio

Revision ID: 9f7a4ff1e4b6
Revises: 
Create Date: 2026-08-16 00:27:39.025509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Las columnas de embeddings se renderizan como pgvector.sqlalchemy.Vector.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9f7a4ff1e4b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Las columnas de embeddings son de tipo `vector`: sin la extensión, el
    # primer CREATE TABLE falla. Va acá y no como paso manual del setup para que
    # una base virgen quede utilizable con un solo `alembic upgrade head`.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_origen', sa.String(), nullable=False),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('metadatos', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hnsw_index_for_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('detalle_error', sa.Text(), nullable=True),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('n_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_usuario_id'), 'documentos', ['usuario_id'], unique=False)
    op.create_table('mazos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tema', sa.String(), nullable=True),
    sa.Column('documento_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mazos_id'), 'mazos', ['id'], unique=False)
    op.create_index(op.f('ix_mazos_usuario_id'), 'mazos', ['usuario_id'], unique=False)
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('caso_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_id'), 'sesiones', ['id'], unique=False)
    op.create_table('chunks_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('pagina', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hnsw_index_chunks_documento', 'chunks_documento', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_chunks_documento_documento_id'), 'chunks_documento', ['documento_id'], unique=False)
    op.create_index(op.f('ix_chunks_documento_id'), 'chunks_documento', ['id'], unique=False)
    op.create_index(op.f('ix_chunks_documento_usuario_id'), 'chunks_documento', ['usuario_id'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.Column('evaluacion_clinica', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_id'), 'evaluaciones', ['id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mazo_id', sa.Integer(), nullable=False),
    sa.Column('anverso', sa.Text(), nullable=False),
    sa.Column('reverso', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('pagina', sa.Integer(), nullable=True),
    sa.Column('aciertos', sa.Integer(), nullable=False),
    sa.Column('fallos', sa.Integer(), nullable=False),
    sa.Column('ultima_revision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mazo_id'], ['mazos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_flashcards_mazo_id'), 'flashcards', ['mazo_id'], unique=False)
    op.create_table('transcripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripciones_id'), 'transcripciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripciones_id'), table_name='transcripciones')
    op.drop_table('transcripciones')
    op.drop_index(op.f('ix_flashcards_mazo_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_evaluaciones_id'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_index(op.f('ix_chunks_documento_usuario_id'), table_name='chunks_documento')
    op.drop_index(op.f('ix_chunks_documento_id'), table_name='chunks_documento')
    op.drop_index(op.f('ix_chunks_documento_documento_id'), table_name='chunks_documento')
    op.drop_index('hnsw_index_chunks_documento', table_name='chunks_documento', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunks_documento')
    op.drop_index(op.f('ix_sesiones_id'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_mazos_usuario_id'), table_name='mazos')
    op.drop_index(op.f('ix_mazos_id'), table_name='mazos')
    op.drop_table('mazos')
    op.drop_index(op.f('ix_documentos_usuario_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_index('hnsw_index_for_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunks')
    # ### end Alembic commands ###
